name: Build Kivy APK with Buildozer

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      # --- Installation SDK avec action GitHub ---
      - name: Install Android SDK
        uses: android-actions/setup-android@v3
        with:
          # Installe plateforme 33, build-tools 33.0.2, et platform-tools
          sdkCommand: "platforms;android-33,platform-tools,build-tools;33.0.2"
          ndkVersion: "25b" # NDK spécifié ici aussi

      - name: Install Buildozer system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git zip unzip wget ant # unzip est nécessaire ici aussi

      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade pip
          pip install cython==0.29.34
          pip install buildozer
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: List files in current directory
        run: ls -la

      # --- Étape de Build MODIFIÉE avec Debug ---
      - name: Build with Buildozer
        run: |
          # --- DEBUG INFO AJOUTÉ ---
          echo "--- Debug Info Before Build ---"
          echo "Variable ANDROID_HOME=$ANDROID_HOME"
          echo "Variable PATH=$PATH"
          echo "Recherche de 'aidl' dans ANDROID_HOME..."
          find $ANDROID_HOME -name aidl -type f -ls || echo "ERREUR DEBUG: aidl non trouvé dans ANDROID_HOME par find"
          which aidl || echo "ERREUR DEBUG: aidl non trouvé dans le PATH par which"
          echo "--- Starting Build ---"
          # --- FIN DEBUG INFO ---

          buildozer --version
          # buildozer clean || echo "Clean failed, continuing build..."
          buildozer -v android debug # -v pour verbose

      # --- Upload Artifact ---
      - name: Upload APK artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk

