name: Build Kivy APK with Buildozer

on: [push, workflow_dispatch] # Déclenche sur push ou manuellement

jobs:
  build:
    runs-on: ubuntu-latest # Utilise un serveur Linux récent

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Utiliser une version Python stable supportée par Kivy/Buildozer

      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11' # Buildozer a besoin de Java (souvent JDK 11)
          distribution: 'temurin' # Distribution OpenJDK populaire

      - name: Install Buildozer and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip ant # Installe les outils de base
          pip install --upgrade pip
          pip install buildozer cython==0.29.34 # Installer buildozer et une version stable de Cython

      - name: Build with Buildozer
        run: |
          buildozer android debug # Lance la construction de l'APK de débogage

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk # Nom de l'archive qui contiendra l'APK
          path: bin/*.apk # Chemin où Buildozer met l'APK créé
