name: Build Kivy APK with Buildozer

# Déclencheurs: sur push vers la branche main OU manuellement
on:
  push:
    branches: [ main, master ] # Adapte si ta branche principale a un autre nom
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # Utilise un serveur Linux

    steps:
      # Étape 1: Récupérer ton code depuis GitHub
      - name: Checkout code
        uses: actions/checkout@v4 # Utilise une version récente

      # Étape 2: Mettre en place Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Version Python stable

      # Étape 3: Mettre en place Java (nécessaire pour les outils Android)
      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17' # Utiliser JDK 17 (recommandé par Android maintenant)
          distribution: 'temurin'

      # Étape 4: Installer Buildozer et ses dépendances système/Python
      - name: Install Buildozer and dependencies
        run: |
          sudo apt-get update -y # Met à jour les listes de paquets Linux
          sudo apt-get install -y git zip unzip wget ant # Outils système requis
          pip install --upgrade pip # Met à jour pip
          pip install buildozer # Installe buildozer
          # Ajoute le chemin local pip au PATH pour que buildozer soit trouvé
          echo "/home/runner/.local/bin" >> $GITHUB_PATH

      # --- ÉTAPE DE DEBUG AJOUTÉE ---
      # Étape 5: Lister les fichiers pour vérifier si buildozer.spec est là
      - name: List files in current directory
        run: ls -la
      # --- FIN ÉTAPE DE DEBUG ---

      # Étape 6: Lancer la construction Buildozer
      - name: Build with Buildozer
        run: |
          buildozer --version # Affiche la version de buildozer
          buildozer android debug # Lance la construction

      # Étape 7: (Ne s'exécute que si la construction réussit) Récupérer l'APK
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk # Nom de l'archive téléchargeable
          path: bin/*.apk # Chemin où se trouve l'APK créé
